name: Run Regression Automated Test Cases for B2B Projects

# Trigger the workflow on pushes to the master branch
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run CI Steps
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (modify version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install required libraries for Playwright and Allure
      - name: Install Libraries
        run: npm install @faker-js/faker crypto-js playwright-msteams-reporter allure-playwright --save-dev

      # Step 5: Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 6: Run Playwright tests with Allure reporter
      - name: Run Playwright Tests
        run: npx playwright test --reporter=allure-playwright

       # Install Allure Commandline
      - name: Install Allure Commandline
        run: npm install allure-commandline --save-dev

      # Step 7: Generate the Allure report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report
      # Step 8: Deploy the Allure report to GitHub Pages
       # Deploy Allure Report
      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
      
