name: Run Regression Automated test cases for B2B Projects

# Trigger the workflow on pushes to the master branch
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run CI Steps
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install required libraries
      - name: Install libraries
        run: npm install @faker-js/faker crypto-js playwright-msteams-reporter allure-playwright --save-dev

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests with Allure reporter
      - name: Run Playwright tests
        run: npx playwright test --reporter=allure-playwright

      # Generate Allure Report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      # Upload Allure Results (Optional: For debugging or storing raw results)
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30

      # Optional: Run Linter (if your project uses one)
      - name: Run Linter
        run: npm run lint
        continue-on-error: true  # Optional: Don't fail the workflow on lint errors
