name: Run Regression Automated test cases for B2B Projects

# Trigger the workflow on pushes to the master branch
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run CI Steps
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js (modify the version as needed)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install required libraries
      - name: Install libraries
        run: npm install @faker-js/faker crypto-js playwright-msteams-reporter

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright tests

      # Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30

      # Checkout Allure history (if needed)
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Optional: Run Linter (if your project uses one)
      - name: Run Linter
        run: npm run lint
        continue-on-error: true  # Optional: Don't fail the workflow on lint errors
