name: CI Workflow

# Trigger the workflow on pushes to any branch
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run CI Steps
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js (modify the version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

      # Optional: Run Linter (if your project uses one)
      - name: Run Linter
        run: npm run lint
        continue-on-error: true  # Optional: Don't fail the workflow on lint errors
